name: ArchBlock
main: com.archivesmc.archblock.Plugin
version: 0.0.3b
author: Gareth Coles
website: https://github.com/TheArchives/ArchBlock

depend: [WGCustomFlags, WorldEdit, WorldGuard]
softdepend: [WatchBlock]

commands:
    # User commands

    friend:
        description: Add another player as a friend, and allow them to edit your blocks
        usage: /<command> [player]
        aliases: [fr, f, wallow]
    friends:
        description: List everyone you've added as a friend
        usage: /<command>
        aliases: [fs, wlist]
    transferblocks:
        description: Transfer all your blocks to another player
        usage: /<command> [player]
        aliases: [tb, transfer, transferb]
        permission: archblock.transfer
    unfriend:
        description: Remove another player from your friends list, preventing them from editing your blocks
        usage: /<command> [player]
        aliases: [ufr, uf, wremove, unwallow]

    # Staff commands

    disownplayer:
        description: Disown all blocks owned by a specific player
        usage: /<command> [player]
        aliases: [dp, disownp]
        permission: archblock.admin
    disownworld:
        description: Disown all blocks on a specific world
        usage: /<command> [world]
        aliases: [dw, disownw]
        permission: archblock.admin
    setowner:
        description: Set a player as the owner of a (WorldEdit) selecion of blocks
        usage: /setowner [player]
        aliases: [so, wtransfer]
        permission: archblock.admin
    transferplayer:
        description: Transfer all owned blocks from one player to another
        usage: /<command> [player] [target player]
        aliases: [transferp]
        permission: archblock.admin

permissions:
    archblock.*:
        description: Gives access to all commands and overrides
        children:
            archblock.admin: true
            archblock.bypass: true
            archblock.transfer: true
    archblock.admin:
        description: Gives a player access to all admin commands
        default: op
    archblock.bypass:
        description: Allows a player to bypass all block protection
        default: op
    archblock.transfer:
        description: Allow a player to transfer ownership of all of their blocks to another player
        default: op
